# Generated by Django 4.1.7 on 2023-05-09 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='menu_images')),
                ('body', models.TextField(blank=True, null=True)),
                ('body_en', models.TextField(blank=True, null=True)),
                ('body_ru', models.TextField(blank=True, null=True)),
                ('body_uz', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, max_length=555, null=True)),
                ('location_en', models.CharField(blank=True, max_length=555, null=True)),
                ('location_ru', models.CharField(blank=True, max_length=555, null=True)),
                ('location_uz', models.CharField(blank=True, max_length=555, null=True)),
                ('phone_number', models.CharField(max_length=55)),
                ('email', models.CharField(blank=True, max_length=55, null=True)),
                ('body', models.TextField(blank=True, null=True)),
                ('body_en', models.TextField(blank=True, null=True)),
                ('body_ru', models.TextField(blank=True, null=True)),
                ('body_uz', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='menu_images')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('title_en', models.CharField(blank=True, max_length=200, null=True)),
                ('title_ru', models.CharField(blank=True, max_length=200, null=True)),
                ('title_uz', models.CharField(blank=True, max_length=200, null=True)),
                ('body', models.TextField(blank=True, null=True)),
                ('body_en', models.TextField(blank=True, null=True)),
                ('body_ru', models.TextField(blank=True, null=True)),
                ('body_uz', models.TextField(blank=True, null=True)),
                ('price', models.CharField(max_length=15)),
                ('category', models.CharField(max_length=55)),
                ('created_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MenuGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='menu_images')),
                ('created_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('num_guests', models.PositiveIntegerField()),
                ('created_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
