# Generated by Django 4.1.7 on 2023-02-19 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cafe", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reservation",
            name="email",
        ),
    ]
