# Generated by Django 4.1.7 on 2023-05-09 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0004_alter_aboutus_options_alter_contact_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='category',
            field=models.CharField(choices=[('foods', 'Foods'), ('drinks', 'Drinks')], max_length=55),
        ),
        migrations.AlterField(
            model_name='menu',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='menu_images'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='price',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
