# Generated by Django 4.1.7 on 2023-03-01 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cafe", "0005_menu_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menu",
            name="price",
            field=models.CharField(max_length=15),
        ),
    ]
