# Generated by Django 4.1.7 on 2023-03-01 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cafe", "0007_contact"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="created_date",
            field=models.DateField(auto_now=True),
        ),
    ]
