# Generated by Django 4.1.7 on 2023-03-01 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cafe", "0008_contact_created_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="MenuGallery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("images", models.ImageField(upload_to="menu_images")),
                ("created_date", models.DateField(auto_now=True)),
            ],
        ),
    ]
