# Generated by Django 4.1.7 on 2023-03-01 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cafe", "0009_menugallery"),
    ]

    operations = [
        migrations.AddField(
            model_name="menu",
            name="created_date",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="contact",
            name="created_date",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="menugallery",
            name="created_date",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
