# Generated by Django 4.1.7 on 2023-03-01 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cafe", "0010_menu_created_date_alter_contact_created_date_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AboutUs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="menu_images")),
                ("body", models.TextField()),
                ("created_date", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
