# Generated by Django 4.1.7 on 2023-03-01 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cafe", "0011_aboutus"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="created_date",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
